baseURL = 'https://example.org/'
languageCode = 'es-ES'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

[params.Author]
    name='Roberto Morais'
    bio='Un desarrollador de software de Golang, PHP y JavaScript'
    image='/images/author/fuenrob.jpg'
    social = [
       { url='https://github.com/FuenRob', icon='fab fa-github' },
       { url='https://www.linkedin.com/in/robercmorais/', icon='fab fa-linkedin' },
       { url='https://x.com/FuenRob', icon='fab fa-x-twitter' }
    ]
    links = [
      { name='Mi canal de YouTube', url='https://www.youtube.com/@FuenRob', description='Tutoriales de programación y desarrollo de software', icon='fab fa-youtube', platform='YouTube' },
      { name='Mi código', url='https://github.com/FuenRob', description='Aquí puedes encontrar mis proyectos', icon='fab fa-github', platform='GitHub'},
      { name='Mi carrera profesional', url='https://www.linkedin.com/in/robercmorais/', icon='fab fa-linkedin', platform='LinkedIn' },
      { name='Sígueme en X', url='https://x.com/FuenRob', icon='fab fa-x-twitter', platform='X' },
      { name='Sígueme en Instagram', url='https://www.instagram.com/fuenrob/', icon='fab fa-instagram', platform='Instagram' },
      { name='Sígueme en TikTok', url='https://www.tiktok.com/@fuenrob', icon='fab fa-tiktok', platform='TikTok' }
    ]

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
